server:
  port: 8400
spring:
  application:
    name: feign-service
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: true
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: true
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true